### ISSUE TITLE
[khabar] Improve error logging to show parameter values

### ISSUE THREAD

**Issue by josjevv** [bulletind/khabar#102]
Example:
401 4.1.3 Bad recipient address syntax

So we know someone sends a wrong email address, but to solve this it helps to know which value is actually being sent.

```
Traceback
goroutine 2888831 [running]:
gopkg.in/simversity/gotracer%2ev1.Tracer.Notify(0x0, 0xc20800b880, 0x14, 0xc208100140, 0x3, 0xc20800b8c0, 0x17, 0xc20800b900, 0x16, 0xc20800b940, ...)
    /home/travis/gopath/src/gopkg.in/simversity/gotracer.v1/error.go:29 +0xcd
log.Panic(0xc2080e5868, 0x1, 0x1)
    /home/travis/.gimme/versions/go/src/log/log.go:320 +0xc4
gopkg.in/bulletind/khabar.v1/utils.(*MailConn).SendEmail(0xc2080e5b28, 0xc2083dc840, 0x1a, 0xc2083efa70, 0x1, 0x1, 0xc2081463c0, 0x1a, 0xc208152000, 0x1807)
    /home/travis/gopath/src/gopkg.in/bulletind/khabar.v1/utils/smtp.go:51 +0x386
gopkg.in/bulletind/khabar.v1/core.emailHandler(0xc2080c5130, 0xc208152000, 0x1807, 0xc208406f30)
    /home/travis/gopath/src/gopkg.in/bulletind/khabar.v1/core/emailer.go:57 +0xd91
gopkg.in/bulletind/khabar.v1/core.sendToChannel(0xc2080c5130, 0xc208152000, 0x1807, 0x8d5e10, 0x5, 0xc208406f30)
    /home/travis/gopath/src/gopkg.in/bulletind/khabar.v1/core/sender.go:35 +0x40a
gopkg.in/bulletind/khabar.v1/core.send(0x8d5f70, 0x5, 0x8d5e10, 0x5, 0xc2080c5130)
    /home/travis/gopath/src/gopkg.in/bulletind/khabar.v1/core/sender.go:117 +0xb9f
gopkg.in/bulletind/khabar.v1/core.SendNotification.func1(0x8d5f70, 0x5, 0x8d5e10, 0x5, 0xc2080c5130, 0xc20841a260)
    /home/travis/gopath/src/gopkg.in/bulletind/khabar.v1/core/sender.go:141 +0x77
created by gopkg.in/bulletind/khabar.v1/core.SendNotification
    /home/travis/gopath/src/gopkg.in/bulletind/khabar.v1/core/sender.go:142 +0x343
```

**Comment by josjevv** [comment]
_From @rubenstolk on August 21, 2015 6:20_

@madhums is this still relevant, otherwise please close?

**Comment by josjevv** [comment]
_From @madhums on August 21, 2015 7:30_

@josjevv is this still valid?

**Comment by josjevv** [comment]
Yeah it is actually, these errors are dependant on its content. WIth the current stacktrace emails only we cannot solve these. E.g. bad recipient syntax, in that case I need to know which user or address has been used. Same for not found. However, it's not high priority anymore as it rarely happens after our last patch to only query active users ;)

But also this does not contain sensitive data actually, so I will move it as well
